name: "dbt_github_metrics"
version: "1.0.0"
config-version: 2

profile: "github_metrics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_test:
    sample:
      +materialized: table
      +engine: MergeTree
